require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Admins::UsersController do

  # This should return the minimal set of attributes required to create a valid
  # Admins::User. As you add validations to Admins::User, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "dashboard" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Admins::UsersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all admins_users as @admins_users" do
      user = Admins::User.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:admins_users)).to eq([user])
    end
  end

  describe "GET show" do
    it "assigns the requested admins_user as @admins_user" do
      user = Admins::User.create! valid_attributes
      get :show, {:id => user.to_param}, valid_session
      expect(assigns(:admins_user)).to eq(user)
    end
  end

  describe "GET new" do
    it "assigns a new admins_user as @admins_user" do
      get :new, {}, valid_session
      expect(assigns(:admins_user)).to be_a_new(Admins::User)
    end
  end

  describe "GET edit" do
    it "assigns the requested admins_user as @admins_user" do
      user = Admins::User.create! valid_attributes
      get :edit, {:id => user.to_param}, valid_session
      expect(assigns(:admins_user)).to eq(user)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Admins::User" do
        expect {
          post :create, {:admins_user => valid_attributes}, valid_session
        }.to change(Admins::User, :count).by(1)
      end

      it "assigns a newly created admins_user as @admins_user" do
        post :create, {:admins_user => valid_attributes}, valid_session
        expect(assigns(:admins_user)).to be_a(Admins::User)
        expect(assigns(:admins_user)).to be_persisted
      end

      it "redirects to the created admins_user" do
        post :create, {:admins_user => valid_attributes}, valid_session
        expect(response).to redirect_to(Admins::User.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved admins_user as @admins_user" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admins::User.any_instance.stub(:save).and_return(false)
        post :create, {:admins_user => { "dashboard" => "invalid value" }}, valid_session
        expect(assigns(:admins_user)).to be_a_new(Admins::User)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admins::User.any_instance.stub(:save).and_return(false)
        post :create, {:admins_user => { "dashboard" => "invalid value" }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested admins_user" do
        user = Admins::User.create! valid_attributes
        # Assuming there are no other admins_users in the database, this
        # specifies that the Admins::User created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(Admins::User).to receive(:update).with({ "dashboard" => "MyString" })
        put :update, {:id => user.to_param, :admins_user => { "dashboard" => "MyString" }}, valid_session
      end

      it "assigns the requested admins_user as @admins_user" do
        user = Admins::User.create! valid_attributes
        put :update, {:id => user.to_param, :admins_user => valid_attributes}, valid_session
        expect(assigns(:admins_user)).to eq(user)
      end

      it "redirects to the admins_user" do
        user = Admins::User.create! valid_attributes
        put :update, {:id => user.to_param, :admins_user => valid_attributes}, valid_session
        expect(response).to redirect_to(user)
      end
    end

    describe "with invalid params" do
      it "assigns the admins_user as @admins_user" do
        user = Admins::User.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admins::User.any_instance.stub(:save).and_return(false)
        put :update, {:id => user.to_param, :admins_user => { "dashboard" => "invalid value" }}, valid_session
        expect(assigns(:admins_user)).to eq(user)
      end

      it "re-renders the 'edit' template" do
        user = Admins::User.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admins::User.any_instance.stub(:save).and_return(false)
        put :update, {:id => user.to_param, :admins_user => { "dashboard" => "invalid value" }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested admins_user" do
      user = Admins::User.create! valid_attributes
      expect {
        delete :destroy, {:id => user.to_param}, valid_session
      }.to change(Admins::User, :count).by(-1)
    end

    it "redirects to the admins_users list" do
      user = Admins::User.create! valid_attributes
      delete :destroy, {:id => user.to_param}, valid_session
      expect(response).to redirect_to(admins_users_url)
    end
  end

end
